### ISSUE TITLE
AdditionalRedirectionsList.csv

### ISSUE THREAD

**Issue by mickeybyte** [aaronparker/FSLogix#10]
Aaron,

I see the Redirections.csv only contains a small number of exclusions, but the additionalredirectionslist.csv contains a lot more exclusions. How can we get those converted into our redirections.xml? Or do we have to do it manually? If I just run ConvertTo-RedirectionsXML it only retrieves the redirections.xml, not the additionalRedirectionsList.csv.

Thanks,
Michiel.

**Comment by aaronparker** [comment]
You can use this syntax:

`ConvertTo-RedirectionsXML -Redirections "https://raw.githubusercontent.com/aaronparker/FSLogix/master/Redirections/AdditionalRedirectionsList.csv" -OutFile "Redirections.xml"`

**Comment by mickeybyte** [comment]
Thanks!
