### ISSUE TITLE
Remove all values from this file.  It's of little utility and a lot of risk to have a generalised exclusion list, people should use default and add in their own exclusions if absolutely necessary.

### ISSUE THREAD

**Issue by JimMoyle** [aaronparker/FSLogix#14]
Review the documentation on [Controlling the Content of the Profile Container](https://docs.fslogix.com/display/20170529/Controlling+the+Content+of+the+Profile+Container) before making this request.

**List the path to add or improve.**
A clear and concise description of what the path is and whether it should be excluded or included. Include in the request:

1. Exclude or include the folder
2. Path relative to the user profile
3. What the Copy action should be
4. A description of what the folder is

**Additional context**
Add any other context on the folder request here.

**Comment by xenadmin** [comment]
Sadly your link @JimMoyle is dead. Any chance there is a version that is still available? Thanks in advance!

**Comment by aaronparker** [comment]
@xenadmin here: [https://docs.microsoft.com/en-au/fslogix/manage-profile-content-cncpt](https://docs.microsoft.com/en-au/fslogix/manage-profile-content-cncpt)

**Comment by aaronparker** [comment]
@JimMoyle which file are you referring to?

**Comment by JimMoyle** [comment]
@aaronparker the csv file containing the default xml settings

**Comment by aaronparker** [comment]
Have made significant changes to the default file. Those exclusions should be relatively safe; however, each one has comments, so if someone implements without reading or testing...
