### ISSUE TITLE
add "%AppData%\Microsoft\Teams\Service Worker\CacheStorage" to targets.xml

### ISSUE THREAD

**Issue by afurtenbacher** [aaronparker/FSLogix#15]
Hi,

MS Teams saves loads of cached data in the folder 
%AppData%\Microsoft\Teams\Service Worker\CacheStorage
I guess it would be helpful to add it to the xml.

Best,
Andreas

**Comment by aaronparker** [comment]
Updated in 54a0d7d9d2f2a70e6feb786182f2e6399528b9b5
