### ISSUE TITLE
Toshiba printer driver cache

### ISSUE THREAD

**Issue by adamlukeind** [aaronparker/FSLogix#17]
Thanks for your efforts

It seems this FSLogix docs link is now broken:

Review the documentation on [Controlling the Content of the Profile Container](https://docs.fslogix.com/display/20170529/Controlling+the+Content+of+the+Profile+Container) before making this request.

We've just come across an issue with Toshiba Universal 2 printer driver from https://www.toshiba-business.com.au/support/drivers/details?term=e-studio5015ac which we use for a few printers

It bloats user profiles by creating loads of folders in TOSHIBA\eSTUDIOX\UNIDRV\Cache relative to the user profile folder

We used to exclude this folder from CItrix UPM profiles, suggest you add to this list as an Exclusion please, Copy action = 0

Thanks

**Comment by aaronparker** [comment]
Added to [https://github.com/aaronparker/FSLogix/blob/main/Redirections/OtherPaths.csv](https://github.com/aaronparker/FSLogix/blob/main/Redirections/OtherPaths.csv)
