### ISSUE TITLE
Running Remove-ProfileData.ps1 as Logon/Logoff script not working

### ISSUE THREAD

**Issue by moar1986** [aaronparker/FSLogix#21]
Hi Aaron,

we were trying to configure your script as a logon/logoff script via GPO but it's not working. I followed your description (https://docs.stealthpuppy.com/docs/fslogix/profile) and edited the script.
The script never launches and fails with an error in eventlog:

_Source: GroupPolicy
Event ID: 1130

Logoff script failed. 
	GPO Name : xxx
	GPO File System Path : \\domain.intranet\sysvol\domain.intranet\Policies\{E62ED9F0-9D5D-4EED-8720-17B7B9AE9F62}\User
	Script Name: Remove-ProfileData.ps1_

It still works if we launch the script manually within the user session. Also other scripts are running fine in our environment.
Do you maybe have any hint for us?

Regards,
Philipp

**Comment by moar1986** [comment]
Hi, just wanted to let you know that I was able to work around this by creating a simple batch file which is calling the powershell script. So instead of using the powershell script as logon script I'm using the batch file.

Regards,
Philipp

**Comment by aaronparker** [comment]
Great to hear. Thanks for posting the update.
