### ISSUE TITLE
Error running \Remove-ContainerData.ps1

### ISSUE THREAD

**Issue by D-Alberto** [aaronparker/fslogix#24]
When i run .\Remove-ContainerData.ps1 -Path \\server\Containers -Targets .\targets.xml 

Out-File : Cannot bind argument to parameter 'FilePath' because it is null.
At D:\bat\vdi\Working\Remove-ContainerData.ps1:445 char:148
+ ... .Elapsed.TotalMilliseconds) ms" | Out-File -FilePath $LogFile -Append
+                                                          ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Out-File], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.OutFileCommand

Out-File : Cannot bind argument to parameter 'FilePath' because it is null.
At D:\bat\vdi\Working\Remove-ContainerData.ps1:446 char:122
+ ... al file size deleted $size MiB" | Out-File -FilePath $LogFile -Append
+                                                          ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Out-File], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.OutFileCommand

Any help would be appreciated

Thx Alberto

**Comment by aaronparker** [comment]
Try using the full path to the XML file

**Comment by D-Alberto** [comment]
Hi, i try but same error. it's a windows server 2016

PS D:\bat\vdi\Working> .\Remove-ContainerData.ps1 -Path \mypath\ -Targets D:\bat\vdi\Working\targets.xml
Out-File : Cannot bind argument to parameter 'FilePath' because it is null.
At D:\bat\vdi\Working\Remove-ContainerData.ps1:445 char:148
+ ... .Elapsed.TotalMilliseconds) ms" | Out-File -FilePath $LogFile -Append
+                                                          ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Out-File], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.OutFileCommand

Out-File : Cannot bind argument to parameter 'FilePath' because it is null.
At D:\bat\vdi\Working\Remove-ContainerData.ps1:446 char:122
+ ... al file size deleted $size MiB" | Out-File -FilePath $LogFile -Append
+                                                          ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Out-File], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.OutFileCommand

**Comment by D-Alberto** [comment]
I find the error for me at line 258
        **$Containers = Get-ChildItem -Path $folder -Recurse -Filter "Profile*.vhdx"**

My profile name does not start with **"profile*"** i changed and it works fine.

It might be useful implement the vhdx file name request?

Thx, Alberto.
