### ISSUE TITLE
Outdated Download URL

### ISSUE THREAD

**Issue by bbalconi** [aaronparker/fslogix#25]
The link to https://stlhppymdrn.blob.core.windows.net/fslogix-agent/x86/FSLogixAppsSetup.exe no longer starts the download. Any ideas on alternatives?

**Comment by aaronparker** [comment]
See `Get-MicrosoftFSLogixApps` in [Evergreen](https://github.com/aaronparker/Evergreen)

**Comment by bbalconi** [comment]
Thank you, Aaron! Evergreen might have several use cases for me.
