### ISSUE TITLE
Script is not executed with GPO with parameter confirm:$false

### ISSUE THREAD

**Issue by robpere** [aaronparker/fslogix#26]
First of all thank you for this creat script!

I have created an user GPO which executes the Profile Cleanup Script. Depending on the parameters that I provide, the script is not automatically executed when you log in. Manually, however, it works without errors. 

In this case the script is executed, but the log files is empty and 1KB. As each line to delete must be confirmed:
\\share\NETLOGON\fslogix\_ProfileCleanup\Remove-ProfileDataSigned.ps1 -Targets "\\share\NETLOGON\fslogix\_ProfileCleanup\targets.xml" -LogPath D:\FSLogix -Verbose

In this case the script is not executed (see paramenter confirm:$false):
\\share\NETLOGON\fslogix\_ProfileCleanup\Remove-ProfileDataSigned.ps1 -Targets "\\share\NETLOGON\fslogix\_ProfileCleanup\targets.xml" -LogPath D:\FSLogix -Confirm:$False -Verbose

The same command with parameter confirm:$false works fine, when exectued manually. Then the logfile is shows all deleted files.

We are using Windows Server 2019 Active Directory and Terminal Servers. 

Have you got an idea why the script can't be executed over GPO with paramenter confirm:$false?

Thank you and Regards,
Roberto

**Comment by aaronparker** [comment]
Try rename the script and remove `Remove-` from the name.

**Comment by robpere** [comment]
When I run the script over GPO with the paramenter "-LogPath D:\FSLogix -Confirm:$False -Verbose", there is an event log entry with ID 1130 (lognscript was not successfully). 

When I run the script over GPO with the paramenter "-LogPath D:\FSLogix -Verbose", the script is executed and an empty logfile is written. 

Verry strange...

**Comment by aaronparker** [comment]
Does modifying `ConfirmImpact` on line [49](https://github.com/aaronparker/fslogix/blob/aa2644872098dad3c70b5cd0428a4971ccf4a555/Profile-Cleanup/Remove-ProfileData.ps1#L49) work?. From:

```powershell
[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'High', HelpUri = 'https://docs.stealthpuppy.com/docs/fslogix/profile')]
```

to:

```powershell
[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Low', HelpUri = 'https://docs.stealthpuppy.com/docs/fslogix/profile')]
```

**Comment by robpere** [comment]
Unfortunately no difference. Still same behavior. 

I tried also to write the option -Confirm:$False direct in the script on line 293, 319, and 347:

from: Remove-Item -Path $thisPath -Force -Recurse -ErrorAction SilentlyContinue 

to: Remove-Item -Path $thisPath -Force -Recurse -ErrorAction SilentlyContinue -Confirm$False

But this generates an error and the script is not executed at all.

**Comment by robpere** [comment]
I dont know if this helps to find the error. I just tried to execute your script in a batch file (script.cmd), which executes your powershell cleanup script with all parameters. When executed as administrator, it works fine. When execute as user, I receive the error in the printscreen. 

---
Translation from german: System.String cannot be converted to the type System.Management.Automation.SwitchParamter, which is required for the Confirm parameter. In line: 1 character: 177
---

![scripterror](https://user-images.githubusercontent.com/23664194/119953383-3df2ea80-bf9e-11eb-9e16-2d47a5649b08.png)

**Comment by robpere** [comment]
I have made a CMD batch file wich executes the powershell script and now it seems to work:

@ECHO OFF
C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe \\domain\NETLOGON\fslogix\_ProfileCleanup\ProfileDataSigned.ps1 -Targets "\\domain\NETLOGON\fslogix\_ProfileCleanup\targets.xml" -LogPath D:\FSLogix -Confirm:$false -Verbose
